version: '3.8'

services:
  zk1:
    image: apachepulsar/pulsar:2.7.2
    hostname: zk1
    ports:
      - "2181:2181"
    volumes:
      - ./data/zk1:/pulsar/data/zookeeper/
      - ./conf/zookeeper.conf:/pulsar/conf/zookeeper.conf
    restart: on-failure
    entrypoint: 
      - sh 
      - -c  
      - |
        mkdir -p data/zookeeper 
        echo 1 > data/zookeeper/myid 
        bin/pulsar zookeeper
    
  zk2:
    image: apachepulsar/pulsar:2.7.2
    hostname: zk2
    ports:
      - "2182:2181"
    volumes:
      - ./data/zk2:/pulsar/data/zookeeper/
      - ./conf/zookeeper.conf:/pulsar/conf/zookeeper.conf
    restart: on-failure
    entrypoint: 
      - sh 
      - -c  
      - |
        mkdir -p data/zookeeper 
        echo 2 > data/zookeeper/myid 
        bin/pulsar zookeeper

  zk3:
    image: apachepulsar/pulsar:2.7.2
    hostname: zk3
    ports:
      - "2183:2181"
    volumes:
      - ./data/zk3:/pulsar/data/zookeeper/
      - ./conf/zookeeper.conf:/pulsar/conf/zookeeper.conf
    restart: on-failure
    entrypoint: 
      - sh 
      - -c  
      - |
        mkdir -p data/zookeeper 
        echo 3 > data/zookeeper/myid 
        bin/pulsar zookeeper

  init-metadata:
      image: apachepulsar/pulsar:2.7.2
      hostname: init-metadata
      restart: on-failure
      entrypoint: bin/pulsar initialize-cluster-metadata \
                --cluster pulsar-cluster-1 \
                --zookeeper zk1:2181,zk2:2181,zk3:2181 \
                --configuration-store zk1:2181,zk2:2181,zk3:2181 \
                --web-service-url http://pulsar-proxy:8080 \
                --broker-service-url pulsar://pulsar-proxy:6650
      depends_on:
        - zk1
        - zk2
        - zk3

  bookie1:
    image: apachepulsar/pulsar:2.7.2
    hostname: bookie1
    ports:
      - "3181:3181"
    volumes:
      - ./data/bookie1:/pulsar/data/bookkeeper/
      - ./conf/bookkeeper.conf:/pulsar/conf/bookkeeper.conf
    restart: on-failure
    entrypoint: bin/pulsar bookie
    depends_on:
      - init-metadata

  bookie2:
    image: apachepulsar/pulsar:2.7.2
    hostname: bookie2
    ports:
      - "3182:3181"
    volumes:
      - ./data/bookie2:/pulsar/data/bookkeeper/
      - ./conf/bookkeeper.conf:/pulsar/conf/bookkeeper.conf
    restart: on-failure
    entrypoint: bin/pulsar bookie
    depends_on:
      - init-metadata

  bookie3:
    image: apachepulsar/pulsar:2.7.2
    hostname: bookie3
    ports:
      - "3183:3181"
    volumes:
      - ./data/bookie3:/pulsar/data/bookkeeper/
      - ./conf/bookkeeper.conf:/pulsar/conf/bookkeeper.conf
    restart: on-failure
    entrypoint: bin/pulsar bookie
    depends_on:
      - init-metadata

  broker1:
    image: apachepulsar/pulsar:2.7.2
    hostname: broker1
    volumes:
      - ./data/broker1:/pulsar/data/broker/
      - ./conf/broker.conf:/pulsar/conf/broker.conf
    restart: on-failure
    entrypoint: bin/pulsar broker
    depends_on:
      - bookie1
      - bookie2
      - bookie3

  broker2:
    image: apachepulsar/pulsar:2.7.2
    hostname: broker2
    volumes:
      - ./data/broker2:/pulsar/data/broker/
      - ./conf/broker.conf:/pulsar/conf/broker.conf
    restart: on-failure
    entrypoint: bin/pulsar broker
    depends_on:
      - bookie1
      - bookie2
      - bookie3

  broker3:
    image: apachepulsar/pulsar:2.7.2
    hostname: broker3
    volumes:
      - ./data/broker2:/pulsar/data/broker/
      - ./conf/broker.conf:/pulsar/conf/broker.conf
    restart: on-failure
    entrypoint: bin/pulsar broker
    depends_on:
      - bookie1
      - bookie2
      - bookie3

  pulsar-proxy:
    image: apachepulsar/pulsar:2.7.2
    hostname: pulsar-proxy
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ./conf/proxy.conf:/pulsar/conf/proxy.conf
    restart: on-failure
    entrypoint: bin/pulsar proxy
    depends_on:
      - broker1
      - broker2

  dashboard:
    image: apachepulsar/pulsar-manager:v0.2.0
    volumes:
      - ./conf/application.properties:/pulsar-manager/pulsar-manager/application.properties
      - ./conf/bkvm.conf:/pulsar-manager/pulsar-manager/bkvm.conf
    ports:
      - "9527:9527"
      - "7750:7750"
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    restart: on-failure
    entrypoint: 
      - sh 
      - -c  
      - |
        /pulsar-manager/entrypoint.sh &
        tail -F /pulsar-manager/pulsar-manager/pulsar-manager.log
    depends_on:
      - pulsar-proxy

  
